# Config borrowed from https://github.com/kn1kn1/language-context-free/blob/master/.circleci/config.yml
version: 2
jobs:
  build:
    working_directory: /tmp/project
    environment:
      # Required:
      DISPLAY: ":99"
      # Configurable
      ATOM_LINT_WITH_BUNDLED_NODE: "true"
      APM_TEST_PACKAGES: ""
      ATOM_CHANNEL: "stable"
    # Machine Setup
    # The following configuration line tells CircleCI to use the specified
    # docker image as the runtime environment for your job.
    # For more information on choosing an image (or alternatively using a
    # VM instead of a container) see https://circleci.com/docs/2.0/executor-types/
    # To see the list of pre-built images that CircleCI provides for most common
    # languages see https://circleci.com/docs/2.0/circleci-images/
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: Update system package lists
        command: sudo apt-get update
    - run:
        name: Install some pre-requisite packages
        command: sudo apt-get --assume-yes --quiet install curl libxss1 libx11-xcb1 libasound2 xvfb
        # NOTE: `libxss1 libx11-xcb1 libasound2` should be removed once atom/atom#16812 lands on stable
    - run:
        name: Start display server for Atom
        command: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16 +extension RANDR
        background: true
    - run:
        name: Download Atom build script
        command: curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
    - run:
        name: Make build script executable
        command: chmod u+x build-package.sh
    - run:
        name: Run package tests
        command: ./build-package.sh
